# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    http_client:
        default_options:
            verify_peer: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
